config/routes.rb
Rails.application.routes.draw do
  resources :apps
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

end

app/models/app.rb
class App < ApplicationRecord
    validates :name, length: { maximum: 14 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :destroy, :update]
  def index
    @app = App.all
  end

  def new
    @app = App.new
  end

  def show
  end

  def create
    @app = App.new(post_params)
    if @app.save
      respond_to do |format|
        format.html {redirect_to app_url(@app) }
      end
    else
      render :new
    end 
  end

  def edit

  end

  def update
    if @app.update(post_params)
      respond_to do |format|
        format.html {redirect_to app_url(@app) }
      end
    else
      render :edit
    end
  end

  def destroy
    @app.destroy
    
  end
  private
  def set_user
    @app = App.find(params[:id])
  end
  def post_params
    params.require(:app).permit(:name, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/_app.html.erb
<div id="<%= dom_id app %>">
  <p>
    <strong>Name:</strong>
    <%= app.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= app.date %>
  </p>

</div>

app/views/apps/_form.html.erb
<%= form_with(model: app) do |form| %>
  <% if app.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
        <% app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.text_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render "form", app: @app %>

<br>

<div>
  <%= link_to "Show this app", @app %> |
  <%= link_to "Back to apps", app_path %>
</div>

app/views/apps/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Apps</h1>

<div id="apps">
  <% @app.each do |app| %>
    <%= render app %>
    <p>
      <%= link_to "Show this app", app %>
    </p>
  <% end %>
</div>

<%= link_to "New app", new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render "form", app: @app %>

<br>

<div>
  <%= link_to "Back to apps", apps_path %>
</div>

app/views/apps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @app %>

<div>
  <%= link_to "Edit this app", edit_app_path(@app) %> |
  <%= link_to "Back to apps", apps_path %>

  <%= button_to "Destroy this app", @app, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>